### ISSUE TITLE
Automatically backup file

### ISSUE THREAD

**Issue by josephsdavid** [morganpartee/codegpt#1]
Since this is a footgun machine, it would be nice to automatically write a backup before starting

**Comment by josephsdavid** [comment]
Like save to `[filename].[extension].bak`

**Comment by josephsdavid** [comment]
or .orig if we are following a git theme

**Comment by morganpartee** [comment]
It moves it to `[filename].[extension].old` by default ;)

But, yeah I'd use git for that
